site_name: optimex
site_description: Time-Explicit Life Cycle Optimization
site_author: Timo Diepers, Jan Tautorus
site_url: https://optimex.readthedocs.io/

repo_name: RWTH-LTT/optimex
repo_url: https://github.com/RWTH-LTT/optimex
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Institute of Technical Thermodynamics, RWTH Aachen University

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    search: lucide/search
  font:
    text: Inter
    code: Consolas
  language: en
  logo: _static/favicons/favicon.svg
  favicon: _static/favicons/favicon.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: lucide/moon-star
        name: Switch to light mode
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    - navigation.sections
    - navigation.tabs
    - navigation.path
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  social:
    - icon: lucide/github
      link: https://github.com/RWTH-LTT/optimex
      name: Open this Repo on GitHub
    - icon: lucide/rocket
      link: https://mybinder.org/v2/gh/RWTH-LTT/optimex/main?urlpath=%2Fdoc%2Ftree%2Fnotebooks%2Fbasic_optimex_example.ipynb
      name: Launch interactive Demo on Binder

extra_css:
  - _static/custom_mkdocs.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  # - material.extensions.preview:
  #     configurations:
  #       - targets:
  #           include:
  #             - api/*
  #             - content/examples/*
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  # - optimize
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          paths: [optimex]
          options:
            docstring_style: numpy
            docstring_section_style: table #table
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            group_by_category: true
            show_if_no_docstring: false
            show_signature: true
            show_signature_annotations: true
            separate_signature: false
            signature_crossrefs: true
            merge_init_into_class: true
            show_source: true
            inherited_members: false
            filters:
              - "!^_"  # exclude private members
              - "!^__"  # exclude magic methods (except __init__)
  - mkdocs-jupyter:
      include_source: true
      execute: false
      allow_errors: false

nav:
  - Home:
    - index.md
    - Changelog: content/changelog.md
    - License: content/license.md
    - Contributing: content/contributing.md
    - Code of Conduct: content/codeofconduct.md
  - How-Tos:
    - Quick Start: content/quickstart.md
    - Installation: content/installation.md
    - Brightway Setup: content/brightway_setup.md
    - Foreground Modeling: content/foreground_modeling.md
    - Optimization Setup: content/optimization_setup.md
    - Constraints: content/constraints.md
    - Postprocessing: content/postprocessing_guide.md
  - Theory: content/theory.md
  - Examples:
    - content/examples/index.md
    - Basic Example: content/examples/basic_optimex_example.ipynb
    - Mini Hydrogen Case: content/examples/mini_hydrogen_case.ipynb
  - API Reference:
    - api/index.md
    - LCA Processor: api/lca_processor.md
    - Converter: api/converter.md
    - Optimizer: api/optimizer.md
    - Postprocessing: api/postprocessing.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.min.js
